import { createPublicClient, http, defineChain } from "viem";
import { env } from "./env.js";
import addresses from "../generated/addresses.json" with { type: "json" };

/// Monad testnet is not in viem's built-in chain list.
export const monadTestnet = defineChain({
  id: 10143,
  name: "Monad Testnet",
  nativeCurrency: { name: "MON", symbol: "MON", decimals: 18 },
  rpcUrls: { default: { http: [env.MONAD_TESTNET_RPC_URL] } },
  blockExplorers: {
    default: { name: "MonadScan", url: "https://testnet.monadscan.com" },
  },
  testnet: true,
});

export const publicClient = createPublicClient({
  chain: monadTestnet,
  transport: http(env.MONAD_TESTNET_RPC_URL),
});

/// Addresses come from the generated file, never from prose in a doc. An earlier,
/// now-orphaned deployment is still referenced in learning.md and still has code
/// on-chain, so pointing at the wrong pair fails silently rather than loudly.
export const CONTRACTS = {
  vault: addresses.EscrowVault as `0x${string}`,
  cam: addresses.CorporateActionManager as `0x${string}`,
  aUSDC: addresses.aUSDC as `0x${string}`,

  /// TLNB "Talon Bond 2026" — the demo ASSET (what the corporate action is about),
  /// never a payment token and deliberately never allowlisted on the CAM. Not in
  /// addresses.json because that file is generated by the deploy script and TLNB was
  /// issued through Cleanverse rather than deployed by us.
  tlnb: "0xbAE642890988C3EF56e77Fb041aFD847A6131d64" as `0x${string}`,
} as const;

/// Blocks the contracts were deployed at — the backfill floor. Scanning from 0
/// would be millions of wasted 99-block pages.
///
/// TLNB's was found by binary-searching getCode rather than assumed: too low wastes
/// thousands of pages, too high silently truncates the cap table, and a truncated cap
/// table is the failure mode that renders beautifully while being fiction.
export const DEPLOY_BLOCKS = {
  vault: 49479524n,
  cam: 49479528n,
  tlnb: 49466189n,
} as const;

/// Addresses are stored lowercase everywhere (DB CHECK constraints enforce it).
/// viem returns checksummed addresses and raw logs return lowercase; mixing the
/// two produces two rows for one holder and a cap table that double-counts.
export function lc(address: string): string {
  return address.toLowerCase();
}
